

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
 

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file ./QuickBites-Food-Delivery-Platform/pom.xml
    - name: Execute Jar file
      run: sudo kill -9 `sudo lsof -t -i:8080` & sudo java -jar /home/ubuntu/actions-runner/_work/QuickBites-aws/QuickBites-aws/QuickBites-Food-Delivery-Platform/target/QuickBites-Food-Delivery-Platform-0.0.1-SNAPSHOT.jar &
   
